nischalshrestha/Unravel

R/rcode_analyzer.R
I was hitting an error whilst trying to install, and it was due to the non-standard character. The package installs now, however, I'm not sure whether this line will still function as you expect it to.  You may have to change the output of the `gsub()` from `"\u2139"` to `"<U+2139>"` or `"&x2139;"`.
=> replace non-standard character

R/datawhats.R, R/rcode_analyzer.R, R/utils.R
This will help with using and testing functions that analyze the fluent code such as `get_dplyr_intermediates`
=> Setup tidylog on package load instead of within shiny server

R/unravel.R, R/utils.R, R/zzz.R, inst/rstudio/addins.dcf
In addition to adding the addin for Unravel, we're also making sure the `{tidylog}` and its respective DataTutor-related options are set on library load time.
=> Added an RStudio addin for easier entry into Unravel (fixes issue #70)

R/rcode_analyzer.R, R/unravel.R, R/unravel_app.R
This PR makes error handling more graceful by attempting to render all lines in Unravel and allowing users to toggle off problematic lines.
For example, consider the following snippet includes a `mean()` function which causes an error since a `data.frame` is not a `numeric` or `logical`:
We simply point out that the step produced an NA, but the warning also appears on the console:
```
Warning in mean.default(.) :
argument is not numeric or logical: returning NA
```
We will render all lines and user can disable `mean()`
=> More graceful error handling

R/unravel_app.R, R/zzz.R
This PR starts addressing issue #73. 
We added logic in the Shiny app for Unravel to display other types of data that can be printed via `shiny::renderPrint()` like vectors and lists. 
This means that we can now have tidyverse code that incorporates steps that have non-dataframe outputs. 
**Dataframe:** 
**Non-Dataframe:**
=> Support basic outputs besides dataframes

R/rcode_analyzer.R, R/unravel_app.R
This PR addresses issue #79 and #66. 
If we have problematic lines such as the example below we point out (for now) that there is an issue with the previous lines:
Then, the user can trace back the issue to the culprit line which is `mean()` in this case:
=> Fix evaluation to render all problematic lines

R/rcode_analyzer.R
This occurred when there was an error in the previous line.
=> Removes redundant appending of a code line in code analysis

R/unravel_app.R, inst/css/style.css, inst/js/explorer.js
This PR address issue #86, where Unravel allowed a user to move / toggle the first dataframe line. 
Effectively, this PR makes changes such that:
- the first line cannot be moved but can be clicked on to view the summary and the dataframe
- the other lines cannot be reordered before the first line, if the user attempts this the reorder does not take place
=> Lock the first line, and prevent reorder of other lines before it

R/rcode_analyzer.R, inst/css/style.css
Previously, Unravel would interpret a single line expression like `data.frame(replicate(5, sample(0:1, 5, rep = TRUE)))` as invalid since `replicate()` is a call and we only checked for first argument being a `data.frame`. Now we just check if the single line when evaluated produces a `data.frame`
=> Some minor fixes for first line lock

DESCRIPTION, R/code_analysis.R, R/styler.R, R/unravel_app.R, R/unravel_helper.R, inst/css/codemirror.css, inst/css/style.css, inst/js/explorer.js, tests/testthat/test-styler.R
This PR addresses issue #95 by adding utility functions to re-style the code, and changes the code overlay to support multi-line output.
Unraveling code with especially long lines currently forces horizontal scrolling which harms UX/readability:
when we could produce a re-formatted line like so:
TODOs:
=> Prettify code

R/styler.R, R/unravel_app.R, inst/js/explorer.js
This PR addresses issue #102 by adding support for highlighting code text for multiple lines and for repeated callout words.
=> Callouts now display for multiline code

.gitignore, DESCRIPTION, R/unravel_app.R, R/utils.R, R/zzz.R, tests/testthat/test-code_analysis.R
This PR address issue #67 by adding logging capability within Unravel for understanding its use or debugging purposes. It's a very basic logging system where we are writing to an `outputs/events.log` file that are based on type of log like `INFO`, `EVENT` for now. The following `options()` are used and can be easily set using a `.Rprofile` or manually:
```r
options(
"unravel.logdir" = "outputs", # the directory name to store log file
"unravel.logfile" = "events.log", # the name of the logfile
"unravel.logging" = FALSE # whether the logging should be turned on/off
)
```
Along with that we converted depends to import to reduce directly loading too many packages, and do not depend on the entire tidyverse. The tests adds library imports for this reason.
=> Add logging

DESCRIPTION, R/callout_df.R, R/unravel_app.R
Fixes issue #105 by adding the column type information in the header to directly mimic output style of `tibble`:
=> Add column type in reactable column headers

R/callout_df.R, R/unravel_app.R
This PR adds support for list columns so we can view them via `reactable` and the ability to add details:
And the user can click on carat icon to expand:
=> Support list columns in reactable

R/utils.R, inst/js/explorer.js
This small PR reduces noise in the logging of click events by not logging cases where we automatically focus on a line for the sake of UX. We do this when unraveling code, whether it's the initial unravel or the structured edit updates by focusing in on the last line of the valid expression. However, this is not user initiated so we make sure to only log if the user performed the click/hover.
We also fixed another inconsistent argument ordering for the `store_log` function invocation and definition.
=> Reduce noise in logging click events

R/code_analysis.R, R/styler.R, R/unravel_app.R, R/utils.R, R/zzz.R, inst/css/style.css, inst/js/explorer.js
This PR addresses issue #30. In particular, the PR adds an ability to invoke the Help pane when a user clicks on a function in the code. Previously there was no way to reach for the function definition and its details, and this provides a way to leverage an already existing/familiar mechanism, the Help pane. This also unburdens us to have to somehow surface function docs up to the UI itself.
We take advantage of the fact that certain Shiny outputs like `plotOutput` allow calling `help()` and even though it's a hack currently, it invokes the Help pane. The forked tidylog will construct all of the HTML for each function call detected within the arguments of the tidyverse verb to make it look like it's a hyperlink text. However, the link will simply alert a JavaScript click listener that …
=> Enable invoking function help

R/unravel_app.R, R/utils.R
This PR fixes the issue where Unravel crashed if options weren't set (it led to a 0 argument vector and broke an `if`). So, we fix that by checking if all the logging options are set. If so, there are no crashes, otherwise ignore and return early. 
We're also adding a log event when a user clicks a function to invoke its docs in the Help pane.
=> Fixes issue #118 by not logging if options are not set

R/unravel_app.R, inst/css/style.css
This PR addresses issue #117 by adding the number of groups on the rowname column header:
This will work for arbitrary number of groups (for e.g. 2 groups):
=> Add info about group numbers in table

R/code_analysis.R, inst/js/explorer.js
This PR fixes issue #126, where the function hyperlink callouts were breaking things. It also turns out that the callouts would also break on sufficiently long lines that break into multiple lines for a given Unravel line. So, the main change done here to combat this and make implementation easier and less brittle is to actually use a smarter regex approach:
- for variable callouts, do a boundary regex but excluding open parens to exclude function calls that may have the same name as variable `(\bcallout\b)(?!\()`
- for function callouts, do a boundary regex `(\bfunction\b)`
=> Fix function and variable code highlights

R/code_analysis.R, R/diagnosis.R
This PR fixes the issue where we weren't properly comparing data.frames/tibbles when only their type is varying, not the values. It also removes the `identifyLoners` (<5 observations of a value) check for data details view because it creates too much noise which could unnecessarily alarm user.
=> Fixes issue #131 and removes a data quality check
